name: Trigger CodeRabbit for Bots

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  trigger:
    if: github.actor == 'Copilot' && github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: Request CodeRabbit Review
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PR_NUM: ${{ github.event.pull_request.number }}
        run: gh pr comment $GH_PR_NUM --body "@coderabbitai review"
